### ISSUE TITLE
HEC-RAS-Python Error: "Invalid class string" - Seeking Assistance

### ISSUE THREAD

**Issue by bimintelligence** [asselapathirana/HEC-RAS-Python#1]
Hello everyone,

I've been working on utilizing HEC-RAS-Python for hydrological simulations, following the steps. I successfully built definitions and imported the RAS-Controller module without any issues. 
![image](https://github.com/asselapathirana/HEC-RAS-Python/assets/73410751/e4052b70-68c6-453b-a961-fb755f5400b6)

However, when attempting to run a specific example, I encountered the following error:

`Traceback (most recent call last):
  File "C:\Users\anaconda3\envs\psslxb\lib\site-packages\win32com\client\dynamic.py", line 84, in _GetGoodDispatch
    IDispatch = pythoncom.connect(IDispatch)
pywintypes.com_error: (-2147221005, 'Invalid class string', None, None)`

`During handling of the above exception, another exception occurred:`

`Traceback (most recent call last):
  File "C:\Users\Downloads\HEC-RAS-Python-master\script1.py", line 6, in <module>
    hec = win32com.client.Dispatch("RAS505.HECRASController")
  File "C:\Users\anaconda3\envs\psslxb\lib\site-packages\win32com\client\__init__.py", line 118, in Dispatch
    dispatch, userName = dynamic._GetGoodDispatchAndUserName(dispatch, userName, clsctx)
  File "C:\Users\anaconda3\envs\psslxb\lib\site-packages\win32com\client\dynamic.py", line 104, in _GetGoodDispatchAndUserName
    return (_GetGoodDispatch(IDispatch, clsctx), userName)
  File "C:\Users\anaconda3\envs\psslxb\lib\site-packages\win32com\client\dynamic.py", line 86, in _GetGoodDispatch
    IDispatch = pythoncom.CoCreateInstance(
pywintypes.com_error: (-2147221005, 'Invalid class string', None, None)`

I'm not familiar with this error, and I'm unsure about its root cause. Has anyone encountered a similar issue and knows how to resolve it? Any help or insights would be greatly appreciated. Thank you!

**Comment by SHAWNZHANGSH** [comment]
I've tested both versions 6.5 and 5.0.7 on Python 3.10, and unfortunately, the same error persists.
